name: android-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build (default: master)'
        required: false
        default: 'master'

jobs:
  pcsx2_android_build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18
      - name: Build PCSX2 for Android
        env:
          ANDROID_STORE_FILE_BASE64: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        run: |
          chmod +x ./gradlew 
          ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pcsx2-android
          path: |
            ./app/build/outputs/apk/release/*.apk
