
name: Mirror Git

on:
  workflow_dispatch:
   inputs:
      android:
        description: 'Whether to trigger an Android build (true/false/auto)'
        required: false
        default: 'true'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Clone GitLab repo
      run: git clone --branch master https://github.com/YGOmod/APKSX2.git mirror

    - name: Copy GitHub Action file to cloned repo
      run: |
        mkdir -p mirror/.github/workflows/
        mkdir -p mirror/app/src/main/assets/bios/
        cp .github/workflows/mirror.yml mirror/.github/workflows/
        cp .github/workflows/build.yml mirror/.github/workflows/
        cp .github/workflows/android-build.yml mirror/.github/workflows/
        cp app/src/main/assets/bios/dafffb0d.bin mirror/app/src/main/assets/bios/
        cp app/src/main/assets/bios/dafffb0d.nvm mirror/app/src/main/assets/bios/
        cp app/src/main/assets/bios/dafffb0d.mec mirror/app/src/main/assets/bios/
        
        
    

    - name: Commit and force push to GitHub
      run: |
        cd mirror
        rm -rf app/src/main/assets/bios/scph39001.bin
        rm -rf app/src/main/assets/bios/scph39001.nvm
        rm -rf app/src/main/assets/bios/scph39001.mec
        git remote set-url origin https://github.com/${{ github.repository }}.git
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "Add GitHub Action file"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        branch: ${{ github.ref }}
        github_url: https://github.com
        directory: ./mirror
        force: true
        
